# Generated by Django 5.1.6 on 2025-05-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('History', 'History'), ('Language', 'Language'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
