# Generated by Django 5.1.6 on 2025-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studymaterial_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
